"""Generate the documented TikZ logo package from the supplied outlined SVGs.

Only the SVG subset used by these two sources is accepted. The generated package
is self-contained: thesis compilation needs neither Python nor the SVG files.
"""
import argparse
import hashlib
from pathlib import Path
import re
import textwrap
import xml.etree.ElementTree as ET

ROOT = Path(__file__).resolve().parents[1]
NUMBER = r"[-+]?(?:\d*\.\d+|\d+\.?\d*)(?:[eE][-+]?\d+)?"
TOKEN = re.compile(rf"{NUMBER}|[MmLlHhVvCcZz]")
SVG = '{http://www.w3.org/2000/svg}'


def decimal(value: str) -> str:
    return f'{float(value):.8f}'.rstrip('0').rstrip('.') or '0'


def path_data(data: str) -> str:
    tokens = TOKEN.findall(data)
    if re.sub(r'[\s,]', '', TOKEN.sub('', data)):
        raise ValueError('Unsupported SVG path command')
    # PGF's SVG parser does not accept exponent notation from Inkscape.
    return ' '.join(t if t.isalpha() else decimal(t) for t in tokens)


def artwork(path: Path) -> str:
    lines = []

    def visit(element: ET.Element) -> None:
        transform = element.get('transform')
        if transform:
            match = re.fullmatch(rf'translate\(\s*({NUMBER})[ ,]+({NUMBER})\s*\)', transform)
            if not match:
                raise ValueError(f'Unsupported transform: {transform}')
            lines.append(r'\begin{scope}[shift={(' + match[1] + ',' + match[2] + ')}]')
        if element.tag == SVG + 'path':
            style = {key.strip(): value.strip() for key, value in
                     (item.split(':', 1) for item in element.get('style', '').split(';')
                      if item.strip())}
            allowed = {'fill', 'fill-rule', 'stroke', 'stroke-width',
                       'stroke-linecap', 'stroke-linejoin', 'stroke-dasharray'}
            if set(style) - allowed or style.get('stroke-dasharray', 'none') != 'none':
                raise ValueError(f'Unsupported style: {style}')
            lines.append('% ' + element.get('id', 'path'))
            options = []
            for key, tikz in [('fill', 'fill'), ('stroke', 'draw')]:
                color = style.get(key, 'black' if key == 'fill' else 'none').strip()
                if color == 'none':
                    continue
                if not re.fullmatch(r'#[0-9a-fA-F]{6}', color):
                    raise ValueError(f'Unsupported color: {color}')
                if color.lower() == '#ffffff':
                    options.append(tikz + '=white')
                else:
                    lines.append(r'\sueplogo@setcolor{' + color[1:].upper() + '}{' + tikz + '}')
                    options.append(tikz + '=sueplogo@' + tikz)
            if 'stroke-width' in style:
                options.append('line width=' + style['stroke-width'].strip() + 'pt')
            if style.get('fill-rule', '').strip() == 'evenodd':
                options.append('even odd rule')
            lines.append(r'\path[' + ','.join(options) + '] svg {')
            lines.extend('  ' + line for line in textwrap.wrap(path_data(element.attrib['d']), 96))
            lines.append('};')
        elif element.tag == SVG + 'g' or element.tag == SVG + 'svg':
            for child in element:
                visit(child)
        elif element.tag.startswith(SVG) and element.tag != SVG + 'defs':
            raise ValueError(f'Unsupported SVG element: {element.tag}')
        if transform:
            lines.append(r'\end{scope}')

    visit(ET.parse(path).getroot())
    return '\n'.join(lines)


def generate() -> str:
    sources = [ROOT / 'resources/logo' / name for name in ('suep-emblem.svg', 'suep-name.svg')]
    header = r'''% \iffalse
% Copyright (C) 2026 SUEPThesis contributors.
% Code is distributed under LPPL 1.3c or later; school marks belong to SUEP.
% Generated by scripts/generate-logo.py. Edit the generator or source SVGs.
% \fi
% \section{上海电力大学矢量标识}
% 结构参考 fduthesis-logo.dtx；路径独立来自用户提供的上海电力大学 SVG。
% 学校 VI 来源：\url{https://www.shiep.edu.cn/vi/list.htm}。
% 本宏包不依赖外部图片、校名字体、Inkscape 或 shell-escape。
% \verb|\suepemblem[width=3cm]| 绘制校徽；
% \verb|\suepname[width=8cm]| 绘制校徽与中英文校名的横向组合。
% 默认保留各 SVG 的原色；\texttt{color=black} 等参数用于单色输出。
% \texttt{SUEPRed} 为学校 VI 图示的校徽红：CC0000（RGB 204,0,0）。
% 图示同时标注 CMYK 26,100,100,0；RGB 定义直接采用图示值。
% \texttt{SUEPEmblemRed} 保留独立校徽 SVG 的原始 FF0000。
%    \begin{macrocode}
%<*package>
\NeedsTeXFormat{LaTeX2e}[2022-06-01]
\ProvidesPackage{sueplogo}[2026/10/08 v0.1.0 SUEP vector logos]
\RequirePackage{tikz,graphicx}
\usetikzlibrary{svg.path}
\definecolor{SUEPRed}{HTML}{CC0000}
\definecolor{SUEPEmblemRed}{HTML}{FF0000}
\pgfkeys{/sueplogo/.is family,/sueplogo,
  width/.store in=\sueplogo@width,
  color/.store in=\sueplogo@color}
\def\sueplogo@original{original}
\def\sueplogo@setcolor#1#2{%
  \ifx\sueplogo@color\sueplogo@original
    \definecolor{sueplogo@#2}{HTML}{#1}%
  \else
    \colorlet{sueplogo@#2}{\sueplogo@color}%
  \fi}
\newcommand\sueplogo@draw[3]{%
  \begingroup
  \pgfkeys{/sueplogo/.cd,width=#1,color=original,#3}%
  \resizebox{\sueplogo@width}{!}{%
    \begin{tikzpicture}[x=1pt,y=1pt,yscale=-1,line cap=butt,line join=miter]
      #2%
    \end{tikzpicture}}%
  \endgroup}
\NewDocumentCommand\suepemblem{O{}}{\sueplogo@draw{3cm}{\sueplogo@emblem}{#1}}
\NewDocumentCommand\suepname{O{}}{\sueplogo@draw{8cm}{\sueplogo@name}{#1}}
'''
    chunks = [header]
    for source, name in zip(sources, ('emblem', 'name')):
        chunks.append('% Source SHA-256: ' + hashlib.sha256(source.read_bytes()).hexdigest())
        chunks.append(r'\def\sueplogo@' + name + '{%\n' + artwork(source) + '\n}')
    chunks.append('%</package>\n%    \\end{macrocode}\n\\endinput\n')
    return '\n'.join(chunks)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    target = ROOT / 'suepthesis-logo.dtx'
    content = generate()
    if args.check:
        if target.read_text(encoding='utf-8') != content:
            raise ValueError('Run python scripts/generate-logo.py to update logo paths')
        print('PASS reproducible SVG logo paths')
    else:
        target.write_text(content, encoding='utf-8', newline='\n')


if __name__ == '__main__':
    main()
